49818-standalone import
Amsterdam/GOB-Import pull request #749
Opened 2022-08-30 14:36 UTC by RoelWKramer

AB#49818

2022-08-30 14:40 UTC, RoelWKramer commented on src/Dockerfile
> +RUN rm -rf GOB-Core && git clone --depth=1 --branch generic-arguments https://github.com/Amsterdam/GOB-Core.git
should be branch master, allows easier branch switching when developing.

2022-08-31 10:35 UTC, roel-devries requested changes

2022-08-31 10:35 UTC, roel-devries commented on src/gobimport/__main__.py
> +        help="The mode to use. Defaults to update",
```suggestion
        help="The mode to use. Defaults to full",
```

2022-08-31 10:35 UTC, roel-devries commented on src/gobimport/__main__.py
> +        "--collection",
```suggestion
        "--collection",
        required=True
```

2022-08-31 10:35 UTC, roel-devries commented on src/gobimport/__main__.py
> +        help="The name of the application to import from"
```suggestion
        required=False,
        help="The name of the application to import from"
```

2022-08-31 11:29 UTC, RoelWKramer commented on src/gobimport/__main__.py
> +        required=True
```suggestion
        required=True,
```

2022-08-31 11:41 UTC, roel-devries approved these changes

2022-08-31 11:42 UTC, merged